import fs from "node:fs";
import path from "node:path";
import type { DbAdapter } from "./DbAdapter.js";

interface ColumnRow {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: string;
}

const POSTGRES_QUERY = `
  SELECT table_name, column_name, data_type, is_nullable
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position
`;

const MSSQL_QUERY = `
  SELECT TABLE_NAME as table_name, COLUMN_NAME as column_name, DATA_TYPE as data_type, IS_NULLABLE as is_nullable
  FROM INFORMATION_SCHEMA.COLUMNS
  ORDER BY TABLE_NAME, ORDINAL_POSITION
`;

function sqlTypeToTs(dataType: string): string {
  const t = dataType.toLowerCase();
  if (/(int|numeric|decimal|float|double|real|money)/.test(t)) return "number";
  if (/(bool)/.test(t)) return "boolean";
  if (/(date|time)/.test(t)) return "string";
  return "string";
}

function toPascalCase(name: string): string {
  return name.replace(/(^|_)([a-z])/g, (_m, _p1, c: string) => c.toUpperCase());
}

export async function introspect(db: DbAdapter, connectionName: string, outFile: string): Promise<void> {
  const query = db.dialect === "postgres" ? POSTGRES_QUERY : MSSQL_QUERY;
  const rows = await db.query<ColumnRow>(query);

  const byTable = new Map<string, ColumnRow[]>();
  for (const row of rows) {
    const list = byTable.get(row.table_name) ?? [];
    list.push(row);
    byTable.set(row.table_name, list);
  }

  let out = `// Generated by "apitest db:introspect --connection ${connectionName}". Do not hand-edit — regenerate instead.\n\n`;
  for (const [table, columns] of byTable) {
    out += `export interface ${toPascalCase(table)} {\n`;
    for (const col of columns) {
      const optional = col.is_nullable === "YES" ? "?" : "";
      out += `  ${col.column_name}${optional}: ${sqlTypeToTs(col.data_type)};\n`;
    }
    out += `}\n\n`;
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, out, "utf-8");
}
